spring:
  datasource:
    url: jdbc:mysql://119.3.150.136:3306/sharedprint?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 12345Asdfg
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8091